# Generated by Django 4.1.7 on 2023-04-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='item_description',
            new_name='item_desc',
        ),
    ]
