# Generated by Django 4.1.7 on 2023-04-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_item_description_items_item_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.nLDShz9SB5YleA3GH5fJJAHaHa?pid=ImgDet&rs=1', max_length=500),
        ),
    ]
